// <auto-generated />
namespace UBA_Network_Security_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Controller1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Controller1));
        
        string IMigrationMetadata.Id
        {
            get { return "202301231840117_Controller1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
