// <auto-generated />
namespace UBA_Network_Security_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateup002 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateup002));
        
        string IMigrationMetadata.Id
        {
            get { return "202302051813172_updateup002"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
